# Generated by Django 3.1.3 on 2020-11-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_produk_deskripsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='nama_anda_sesuai_akun',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produk',
            name='nomor_hp',
            field=models.IntegerField(null=True),
        ),
    ]
