# Generated by Django 3.1.3 on 2020-11-27 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_produk_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produk',
            name='slug',
        ),
    ]
